name: Read from an SQLite database from Postgres.js
on:
  workflow_dispatch:
jobs:
  read-from-sqlite-database-from-postgres-js:
    name: Read from an SQLite database from Postgres.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          # Add brews to the path
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
          # Setup brew environment
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          # Install sqld https://github.com/libsql/sqld
          brew tap libsql/sqld
          brew install sqld-beta
      - uses: pnpm/action-setup@v2
        with:
          version: '7'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Start database in background
        run: sqld -d database.db -p 127.0.0.1:5432 --http-listen-addr=127.0.0.1:8000 &
      - name: Wait for database to start
        run: sleep 10
      - name: Run script
        run: pnpm start
